# config for rbn telnet server
rbn:
  callsign: "HB9HUS" # callsign used for login
  host: "telnet.reversebeacon.net"
  port: 7000
# config for in memory database
db:
  cleanup_period_secs: 900
  max_spot_age_secs: 1800
